// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1Dvy3VGBs9EICthoi2kpKvIsPTJIkPwc',
    appId: '1:894416954179:web:7d5eaff1668134402645f6',
    messagingSenderId: '894416954179',
    projectId: 'sdpecommerceapp',
    authDomain: 'sdpecommerceapp.firebaseapp.com',
    storageBucket: 'sdpecommerceapp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBntbDjlSvSrT0nhizqqGJI5oVgQk6iIo4',
    appId: '1:894416954179:android:f673c9a0e50138432645f6',
    messagingSenderId: '894416954179',
    projectId: 'sdpecommerceapp',
    storageBucket: 'sdpecommerceapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJ0cU5VxgLRiMCSYRuWAQFtT97mXBZ-Pc',
    appId: '1:894416954179:ios:b68ab5d0484e2cff2645f6',
    messagingSenderId: '894416954179',
    projectId: 'sdpecommerceapp',
    storageBucket: 'sdpecommerceapp.appspot.com',
    iosBundleId: 'com.example.flutterECommerce',
  );
}
